17 build login and register section
notdanielrojas/next-to-do-list pull request #18
Opened 2024-11-21 17:33 UTC by notdanielrojas

Creado login and register form, agregado responsive e interacción.

2024-11-22 03:56 UTC, MageLnk requested changes

2024-11-22 16:33 UTC, notdanielrojas commented on app/components/RegisterForm.tsx
> +        onChange={(e) => setUser({ ...user, name: e.target.value })}
Bueno, es la forma en que aprendí trabajando con react pero ayuda a la legibilidad del código aunque igual puedo dejarlo en una función y reutilizarla.

2024-11-23 02:42 UTC, notdanielrojas commented
Quedo a la espera de la 2da revisión wum.

2024-11-25 23:03 UTC, MageLnk approved these changes

2024-11-25 23:03 UTC, merged